services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: q
    volumes:
      - mongo_data:/data/db

  py:
    build:
      context: ..
      dockerfile: docker/Dockerfile.py
    container_name: py-runner
    working_dir: /work
    volumes:
      - ..:/work:cached
    environment:
      MONGO_URI: mongodb://admin:q@mongo:27017/?authSource=admin
      MONGO_DB_MARKET: market
      MARKET_DATA_DIR: "practices/p6/data"
      MARKET_OUTPUT_DATA: "practices/p6/output"
    depends_on:
      - mongo
    tty: true
    stdin_open: true

volumes:
  mongo_data:

